// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zftvlzzgxbghtzwsnbnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmdHZsenpneGJnaHR6d3NuYm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDU0MjcsImV4cCI6MjA2Nzg4MTQyN30.vQFQBae6Qg3ZNMmROLrEw7_1ZeQ0CTNwUImRM7PjxKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});